# docker run -p 9000:9000 -p 9001:9001 -v ./data:/data minio/minio server /data --console-address ":9001"
version: '3'
services:
  minio1:
    image: minio/minio
    command: server http://minio{1...3}/data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data1:/data
    environment:
      MINIO_ACCESS_KEY: your-access-key
      MINIO_SECRET_KEY: your-secret-key
    networks:
      minio-net:

  minio2:
    image: minio/minio
    command: server http://minio{1...3}/data --console-address ":9001"
    volumes:
      - ./data2:/data
    environment:
      MINIO_ACCESS_KEY: your-access-key
      MINIO_SECRET_KEY: your-secret-key
    networks:
      minio-net:

  minio3:
    image: minio/minio
    command: server http://minio{1...3}/data --console-address ":9001"
    volumes:
      - ./data3:/data
    environment:
      MINIO_ACCESS_KEY: your-access-key
      MINIO_SECRET_KEY: your-secret-key
    networks:
      minio-net:

networks:
  minio-net: