# docker run -p 9000:9000 -p 9001:9001 -v ./data:/data minio/minio server /data --console-address ":9001"
version: '3'
services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data:/data
    environment:
      MINIO_ACCESS_KEY: your-access-key
      MINIO_SECRET_KEY: your-secret-key
    networks:
      minio-net:
volumes:
  data:
networks:
  minio-net: